CREATE TABLE BTC (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR (10) NOT NULL,
    price DECIMAL NOT NULL,
    timestamp DATE NOT NULL
);

CREATE TABLE ETH (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR (10) NOT NULL,
    price DECIMAL NOT NULL,
    timestamp DATE NOT NULL
);

CREATE TABLE DOGE (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR (10) NOT NULL,
    price DECIMAL(10,4) NOT NULL,
    timestamp DATE NOT NULL
);

CREATE TABLE LTC (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR (10) NOT NULL,
    price DECIMAL(10,1) NOT NULL,
    timestamp DATE NOT NULL
);

CREATE TABLE XRP (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR (10) NOT NULL,
    price DECIMAL(10,4) NOT NULL,
    timestamp DATE NOT NULL
)